# Generated by Django 4.2.6 on 2023-11-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "User_Id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("Username", models.CharField(max_length=200, unique=True)),
                ("First_Name", models.CharField(max_length=200)),
                ("Last_Name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product_Inv",
            fields=[
                ("Product_Id", models.IntegerField(primary_key=True, serialize=False)),
                ("Product_Name", models.CharField(max_length=200)),
                ("Product_Description", models.CharField(max_length=200)),
                ("Product_Quantity", models.IntegerField()),
                ("Prodcut_Price", models.IntegerField()),
                (
                    "User_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User_Id_Product_Inv",
                        to="Assignment_4_App.users",
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Username_Product_Inv",
                        to="Assignment_4_App.users",
                        to_field="Username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alterations",
            fields=[
                ("Time_Stamp", models.DateTimeField(primary_key=True, serialize=False)),
                (
                    "Product_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Assignment_4_App.product_inv",
                    ),
                ),
                (
                    "User_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User_Id_Alterations",
                        to="Assignment_4_App.users",
                    ),
                ),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Username_Alterations",
                        to="Assignment_4_App.users",
                        to_field="Username",
                    ),
                ),
            ],
        ),
    ]
